# Generated by Django 4.2 on 2023-05-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_books_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.TextField(default='test content'),
            preserve_default=False,
        ),
    ]
